version: '3'

services:
  frontend:
    build: ../frontend
    ports:
      - "9000:9000"
  payserver:
    depends_on:
      - redis-players
    build: .
    ports:
      - "7000:7000"
  redis-players:
    image: redis
    ports:
      - "6379:6379"
